
name: Daily Signals Snapshot
on:
  schedule:
    - cron: "0 6 * * *"  # 06:00 UTC daily
  workflow_dispatch:

jobs:
  build-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python - <<'PY'
import json, pandas as pd
from core.settings import TOP5, DEFAULT_DAYS
from core.data import fetch_market_chart, fetch_markets_snapshot
from core.signals import compute_signals, simple_risk_flag
from datetime import datetime

coin_ids = [c["id"] for c in TOP5]
mkt = fetch_markets_snapshot(coin_ids)
rows = []
for c in TOP5:
    cid, sym = c["id"], c["symbol"]
    df = fetch_market_chart(cid, days=DEFAULT_DAYS)
    _, snap = compute_signals(df)
    mc = float(mkt.get(cid, {}).get("market_cap") or 0)
    vol = float(mkt.get(cid, {}).get("total_volume") or 0)
    rows.append({
        "symbol": sym, "coin_id": cid, "signal": snap["signal"], "reason": snap["reason"],
        "price_usd": snap["price"], "rsi14": snap["RSI14"], "sma20": snap["SMA20"], "sma50": snap["SMA50"],
        "risk": simple_risk_flag(mc, vol), "market_cap": mc or None, "volume_24h": vol or None,
        "updated_utc": datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    })
with open("signals_daily.json","w",encoding="utf-8") as f:
    json.dump(rows, f, ensure_ascii=False, indent=2)
PY
      - name: Commit JSON
        run: |
          git config user.name "actions-bot"
          git config user.email "actions@users.noreply.github.com"
          git add signals_daily.json
          git commit -m "chore: update daily signals" || echo "No changes"
          git push
